version: "2.1"
services:

        testrpc:
                build:
                        context: ./feathers-giveth
                        dockerfile: Dockerfile-testrpc
                ports:
                  - "8546:8546"
                healthcheck:
                        test: "nc -z localhost 8546"
                        interval: 5s
                        timeout: 5s
                        retries: 3
        feathers-giveth:
                build: ./feathers-giveth
                ports:
                 - "3030:3030"
                depends_on:
                  testrpc:
                    condition: service_healthy
                healthcheck:
                        test: "nc -z localhost 3030"
                        interval: 5s
                        timeout: 5s
                        retries: 3
        giveth-dapp:
                build: ./giveth-dapp
                ports:
                 - "3010:3010"
                depends_on:
                  feathers-giveth:
                    condition: service_healthy

