version: "2"
services:
        testrpc:
                build:
                        context: ./feathers-giveth
                        dockerfile: Dockerfile-testrpc
#               ports:
#                 - "8546:8546"
        feathers-giveth:
                build: ./feathers-giveth
                ports:
                 - "3030:3030"
                depends_on:
                 - testrpc
        giveth-dapp:
                build: ./giveth-dapp
                ports:
                 - "3010:3010"
                depends_on:
                 - feathers-giveth

