FROM node

RUN git clone https://github.com/nixbox/feathers-giveth.git
WORKDIR feathers-giveth
RUN npm install

EXPOSE 8546

#RUN sed -i -e '2s/localhost/testrpc/' config/default.json

CMD yarn testrpc

